language: c

compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
#this part is retrieved from PX4
before_script:
  - wget https://launchpadlibrarian.net/186124160/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - tar -jxf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_8-2014q3/bin
script:
  - arm-none-eabi-gcc --version
  - echo $PATH
  - make
  - arm-none-eabi-size firmware.elf
