language: c

compiler: gcc

before_install:
  - sudo apt-get update
  - wget https://launchpadlibrarian.net/186124160/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
install:
  - sudo apt-get install build-essential
  - tar -xf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - ls ./gcc-arm-none-eabi-4_8-2014q3/bin
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_8-2014q3/bin
before_script:
  - arm-none-eabi-gcc --version
  - echo $PATH
script:
  - make
  - arm-none-eabi-size firmware.elf
